DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS photo;
DROP TABLE IF EXISTS plate;
DROP TABLE IF EXISTS format;
DROP TABLE IF EXISTS scan;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  hsh_passwd TEXT
);

CREATE TABLE photo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file_name TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_labeled BOOLEAN DEFAULT "0",
  longitude FLOAT NOT NULL,
  latitude FLOAT NOT NULL
);

CREATE TABLE format (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text_sample TEXT NOT NULL,
  country TEXT NOT NULL,
  regex TEXT NOT NULL
);

CREATE TABLE plate (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text_plate TEXT NOT NULL,
  format_id INTEGER NOT NULL,
  note TEXT,
  flagged BOOLEAN DEFAULT "0",
  FOREIGN KEY (format_id) REFERENCES format(id) ON DELETE SET NULL
);

CREATE TABLE scan (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  photo_id INTEGER NOT NULL,
  plate_id INTEGER,
  accuracy FLOAT NOT NULL DEFAULT 0,
  is_deleted BOOLEAN DEFAULT "0",
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL,
  FOREIGN KEY (photo_id) REFERENCES photo(id) ON DELETE CASCADE,
  FOREIGN KEY (plate_id) REFERENCES plate(id) ON DELETE SET NULL
);